import os

import argparse
from datetime import datetime

outputDir = 'outputDir'
cloneMap = 'cloneMap'
inputDir = 'inputDir'
landmask = 'landmask'
institution = 'institution'
title = 'title'
description = 'description'
lowResData = 'lowResData'
highResData = 'highResData'

parser = argparse.ArgumentParser()
parser.add_argument(f"--name", type=str)
parser.add_argument(f"--base_ini", type=str)
parser.add_argument(f"--{outputDir}", type=str)
parser.add_argument(f"--{cloneMap}", type=str)
parser.add_argument(f"--{inputDir}", type=str)
parser.add_argument(f"--{landmask}", default='None', type=str)
parser.add_argument(f"--{institution}", default='""', type=str)
parser.add_argument(f"--{title}", default='""', type=str)
parser.add_argument(f"--{description}", default='""', type=str)
parser.add_argument(f"--{lowResData}", default='global_30min', type=str)
parser.add_argument(f"--{highResData}", default='global_05min', type=str)


if __name__ == "__main__":
    args = parser.parse_args()
    now = datetime.now()

    with open(vars(args)['base_ini'], 'r') as handle:
        base_ini = handle.read()

    full_ini = base_ini.format(**vars(args))
    full_ini += f'\n# Automatically generated by create_ini_config.py from "{vars(args)["base_ini"]}" on '
    full_ini += now.strftime("%d/%m/%y at %H:%M")

    filename = now.strftime("%y%m%d%H%M") + f'_{vars(args)["name"]}_' + os.path.split(vars(args)['base_ini'])[-1]

    with open(filename, 'w') as handle:
        handle.write(full_ini)

    print(filename)
